Loaded 1 valid graphs.
Bug file id: 641d6243
Performing initial feedback checks...
Initial feedback check passed for graph 1.
/home/iany/.local/lib/python3.10/site-packages/coverage/inorout.py:519: CoverageWarning: Module networkx was previously imported, but not measured (module-not-measured)
  self.warn(msg, slug="module-not-measured")
71, 0.5982301235198975
34, 1.0233054161071777
1, 1.4436814785003662
2, 3.1109416484832764
2, 3.9320130348205566
2, 85.89866137504578
Ctrl+C pressed, finalizing...
Finalizing process...
count 17676
There were 126 graphs saved in the corpus.
Time spent: 120.002 minutes.
Exception: {0: "Error: 'int' object has no attribute 'is_directed'", <networkx.classes.graph.Graph object at 0x7f89974820b0>: 'NetworkX Error: Disconnected graph: Ambiguous solution for bipartite sets.', <networkx.classes.graph.Graph object at 0x7f8997482080>: 'Disconnected graph: Ambiguous solution for bipartite sets.', <networkx.classes.graph.Graph object at 0x7f89d4468520>: 'NetworkX Error: Graph is not bipartite.', <networkx.classes.graph.Graph object at 0x7f89d4468a30>: 'Graph is not bipartite.', <networkx.classes.graph.Graph object at 0x7f89d446b160>: "NetworkX Error: ('Connectivity is undefined ', 'for the null graph.')", <networkx.classes.graph.Graph object at 0x7f89d21625c0>: "('Connectivity is undefined ', 'for the null graph.')"}
Exception graphs saved to /home/iany/GraphFuzz/Log/max_matching_corpus_exceptions.pkl
Total Bugs Found:
Checking completed.