Loaded 1 valid graphs.
Bug file id: f260545e
Performing initial feedback checks...
/home/iany/.local/lib/python3.10/site-packages/coverage/inorout.py:519: CoverageWarning: Module networkx was previously imported, but not measured (module-not-measured)
  self.warn(msg, slug="module-not-measured")
4, 0.0815572738647461
Initial feedback check passed for graph 1.
50, 0.4261953830718994
2, 0.9613041877746582
2, 3.4921257495880127
2, 16.535329580307007
/home/iany/.local/lib/python3.10/site-packages/coverage/inorout.py:519: CoverageWarning: Module networkx was previously imported, but not measured (module-not-measured)
  self.warn(msg, slug="module-not-measured")
50, 16.853073596954346
2, 54.54185891151428
Ctrl+C pressed, finalizing...
Finalizing process...
count 40013
There were 7 graphs saved in the corpus.
Time spent: 119.996 minutes.
Exception: {0: "'int' object has no attribute 'is_directed'", <networkx.classes.graph.Graph object at 0x7f804f591660>: 'Graph is not bipartite.', <networkx.classes.graph.Graph object at 0x7f804f5932e0>: 'Disconnected graph: Ambiguous solution for bipartite sets.', <networkx.classes.graph.Graph object at 0x7f804e16f040>: "('Connectivity is undefined ', 'for the null graph.')"}
Exception graphs saved to /home/iany/GraphFuzz/Log/max_matching_corpus_exceptions.pkl
Total Bugs Found:
Checking completed.
